### ISSUE TITLE
Question on MapMetaInfo mixin

### ISSUE THREAD

**Issue by rylanharper** [timbenniks/timbenniks2020-nuxt#1]
Hey Tim! 👋

I really appreciate you making your website opensource! I have used Prismic and Nuxt many times in the past, but with the new Prismic/Nuxt Module I wanted to try some Graphql action for a change. So far its going great, I have successfully queried all my data and posts/projects and am working towards launching a portfolio of my own once I get all the styling done. Although I have structured my project and lot differently and mainly am using your repo as a reference for querying data/slices, I am interested in the mapMetaInfo mixin. I am having trouble wrapping my head around it for the most part.. mainly the first `getPropType` function.  

I was wondering if you could you help explain what that is exactly looking for? Perhaps I need to structure my slices differently on the Prismic side of things, but it seems to me that it is searching for the first primary slice type on each page (or maybe its not)😆 Also I see you have a general_card and twitter_card slice type within the index.vue—those needed for the Meta mixin as well? I know this all sounds very noobish, but I generally just place all my meta data (og and twitter info) in my nuxt.config lol so creating meta info per page/post is new to me. 

I will likely make a more simple version of the mapMetaInfo mixin once I get a grasp on it.

Any help would be great!

**Comment by timbenniks** [comment]
Hey, thanks for the question. Not noobish at all! Without knowing my data structure this is hard.

See below the JSON of how I set up the slices for general card and twitter card. A page tab in Prismic (Social Cards) with two slices.

The mapMetaInfo function is not a mixin but just a little helper function. It's get's certain data (see example below) and the `getPropType` function looks for some data inside of it. With the Slice SJON data below it should start to make more sense.

For example (`this document.data' are homepage content and slices): 
```javascript
mapMetaInfo(this.document.data, 'home', this.$router.currentRoute)
```

Slices JSON:
```json
{
	"Social Cards": {
		"body": {
			"type": "Slices",
			"fieldset": "Slice zone",
			"config": {
				"labels": {},
				"choices": {
					"general_card": {
						"type": "Slice",
						"fieldset": "General Card",
						"description": "General Social card",
						"icon": "art_track",
						"non-repeat": {
							"title": {
								"type": "StructuredText",
								"config": {
									"single": "heading1",
									"label": "Title",
									"placeholder": "Title..."
								}
							},
							"description": {
								"type": "StructuredText",
								"config": {
									"single": "paragraph",
									"label": "Description",
									"placeholder": "Description..."
								}
							},
							"image": {
								"type": "Image",
								"config": {
									"constraint": {
										"width": null,
										"height": null
									},
									"thumbnails": [],
									"label": "Image"
								}
							}
						},
						"repeat": {}
					},
					"twitter_card": {
						"type": "Slice",
						"fieldset": "Twitter Card",
						"description": "Twitter summary card with image",
						"icon": "subtitles",
						"non-repeat": {
							"card_type": {
								"type": "Select",
								"config": {
									"options": ["Standard Summary Card", "Summary Card with Large Image"],
									"default_value": "Standard Summary Card",
									"label": "Card type"
								}
							},
							"twitter_handle": {
								"type": "Text",
								"config": {
									"label": "Twitter Handle",
									"placeholder": "Twitter handle..."
								}
							},
							"title": {
								"type": "StructuredText",
								"config": {
									"single": "paragraph",
									"label": "Title",
									"placeholder": "Twitter Card Title..."
								}
							},
							"description": {
								"type": "StructuredText",
								"config": {
									"single": "paragraph",
									"label": "Description",
									"placeholder": "Twitter Card Description..."
								}
							},
							"image": {
								"type": "Image",
								"config": {
									"constraint": {
										"width": null,
										"height": null
									},
									"thumbnails": [],
									"label": "Image"
								}
							}
						},
						"repeat": {}
					}
				}
			}
		}
	}
}```

**Comment by rylanharper** [comment]
Ah okay got it. I just tried that out and its working great! 🚀

Just a few more questions about this.. 
1) I see that you only query the twitter/general card on your `index.vue`. Why not on other pages? Do you have a Social Cards tab for each single/repeatable page type?
2) For social images (twitter, etc.) I am guessing its best practice to add in an image that matches the standard twitter post size dimensions? Adobe/Figma for example states that that is 1012x506.. Or does that not really matter much? 
3) For optimal SEO, is it best to match all titles and descriptions on the social cards as closely as possible to each page/post title and description? 

Sorry to be so specific, I just need some answers on these last things so I am get up and running this Meta mixin/helper lol!

**Comment by timbenniks** [comment]
1. I have that tab on each type. Just so I can control exactly what I do with the metadata. I does look like I only query it on the homepage but that's due to a special graph query. I actually query it on every page. This get's data and slices: `const document = (await $prismic.api.getSingle('speaking')).data` for example.
2. I just use the 16/9 one. They seem to work. I however gave myself the option to have a different picture for both cards. Just to have the flexibility.
3. I 90% of the time match them. But I gave myself the option to be able to change it. I add my name to all titles for in the browser and for SEO but for twitter card I don't add my name. For example :)

**Comment by rylanharper** [comment]
Awesome. Thats exactly what I needed to know to get started with this Meta mixin/helper.

Really appreciate all the help! Your a wizard Tim keep up the great work! 🔥 💯

**Comment by timbenniks** [comment]
No worries man! 👍 Maybe consider this: https://timbenniks.dev/sponsor-me/ or follow me on YouTube: https://youtube.com/timbenniks 🔥
